apiVersion: v1
kind: ServiceAccount
metadata:
  name: firefighter-ingress
  namespace: firefighter
  labels:
    app.kubernetes.io/name: firefighter
    app.kubernetes.io/component: ingress-controller